import { useState, useEffect } from "react";
import Navbar from "../components/Navbar";
import api from "../services/api";
import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
  Legend
} from "recharts";

function Analytics() {
  const [topLearners, setTopLearners] = useState([]);
  const [batchPerformance, setBatchPerformance] = useState([]);
  const [weakLearners, setWeakLearners] = useState([]);
  
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  const fetchAnalytics = async () => {
    try {
      setLoading(true);
      setError("");

      // Fetch from the Spring Boot analytics endpoints
      const [topRes, batchRes, weakRes] = await Promise.all([
        api.get("/analytics/top"),
        api.get("/analytics/batch-performance"),
        api.get("/analytics/weak")
      ]);

      // 1. Process Top Learners
      setTopLearners(topRes.data?.data || []);

      // 2. Process Batch Performance (Convert {"Batch_A": 74.2} to [{ name: "Batch_A", Average: 74.2 }])
      const batchData = batchRes.data?.data || {};
      const formattedBatch = Object.entries(batchData).map(([batchName, avgScore]) => ({
        name: batchName,
        "Average Score": Math.round(avgScore)
      }));
      setBatchPerformance(formattedBatch);

      // 3. Process Weak Learners
      setWeakLearners(weakRes.data?.data || []);
    } catch (err) {
      console.error(err);
      setError(
        "Failed to load real-time analytics. Please verify both Spring Boot (8081) and FastAPI (8000) servers are running, and that you have run the ETL pipeline once."
      );
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchAnalytics();
  }, []);

  const totalWeakCount = weakLearners.length;

  return (
    <>
      <Navbar />

      <div className="screen">
        <div className="section-title">Analytics Intelligence Dashboard</div>
        <div className="section-sub" style={{ marginBottom: "25px" }}>
          Real-time aggregated intelligence generated by the FastAPI ETL and Spring Boot analytics pipeline
        </div>

        {error && (
          <div
            style={{
              background: "rgba(255, 77, 125, 0.15)",
              color: "#ff4d7d",
              padding: "16px",
              borderRadius: "12px",
              marginBottom: "25px",
              border: "1px solid rgba(255, 77, 125, 0.3)",
              fontSize: "15px"
            }}
          >
            {error}
          </div>
        )}

        {/* Overview Widgets */}
        <div className="stats-grid" style={{ marginBottom: "25px" }}>
          <div className="stat-card">
            <div className="stat-num" style={{ color: "#00e38c" }}>
              {loading ? "..." : topLearners.length}
            </div>
            <div className="stat-label">Identified Top Achievers</div>
          </div>

          <div className="stat-card">
            <div className="stat-num" style={{ color: "#ffb800" }}>
              {loading ? "..." : batchPerformance.length}
            </div>
            <div className="stat-label">Batches Analyzed</div>
          </div>

          <div className="stat-card">
            <div className="stat-num" style={{ color: totalWeakCount > 0 ? "#ff4d7d" : "#fff" }}>
              {loading ? "..." : totalWeakCount}
            </div>
            <div className="stat-label">Students Below Grade (At Risk)</div>
          </div>
        </div>

        {/* Charts Grid */}
        <div className="two-grid" style={{ marginBottom: "25px" }}>
          {/* Chart 1: Batch Performance */}
          <div className="card">
            <h2 style={{ marginBottom: "20px" }}>Average Performance by Batch</h2>
            <div style={{ width: "100%", height: "280px" }}>
              {loading ? (
                <div className="chart-box">Aggregating batch averages...</div>
              ) : batchPerformance.length === 0 ? (
                <div className="chart-box">No batch data available.</div>
              ) : (
                <ResponsiveContainer width="100%" height="100%">
                  <BarChart data={batchPerformance}>
                    <CartesianGrid strokeDasharray="3 3" stroke="#25294a" />
                    <XAxis dataKey="name" stroke="#9ca3d5" />
                    <YAxis stroke="#9ca3d5" domain={[0, 100]} />
                    <Tooltip
                      contentStyle={{
                        background: "#111325",
                        borderColor: "#25294a",
                        borderRadius: "8px",
                        color: "#fff"
                      }}
                    />
                    <Legend />
                    <Bar dataKey="Average Score" fill="#6c63ff" radius={[6, 6, 0, 0]} />
                  </BarChart>
                </ResponsiveContainer>
              )}
            </div>
          </div>

          {/* Chart 2: Weak Learners */}
          <div className="card">
            <h2 style={{ marginBottom: "20px" }}>Risk Radar: Weak Learners Coding Averages</h2>
            <div style={{ width: "100%", height: "280px" }}>
              {loading ? (
                <div className="chart-box">Identifying at-risk profiles...</div>
              ) : weakLearners.length === 0 ? (
                <div className="chart-box" style={{ color: "#00e38c" }}>Zero at-risk students found! Excellent work.</div>
              ) : (
                <ResponsiveContainer width="100%" height="100%">
                  <BarChart
                    data={weakLearners.map((item) => ({
                      name: `ID #${item.learner_id}`,
                      "Coding Score": item.coding_score
                    }))}
                  >
                    <CartesianGrid strokeDasharray="3 3" stroke="#25294a" />
                    <XAxis dataKey="name" stroke="#9ca3d5" />
                    <YAxis stroke="#9ca3d5" domain={[0, 100]} />
                    <Tooltip
                      contentStyle={{
                        background: "#111325",
                        borderColor: "#25294a",
                        borderRadius: "8px",
                        color: "#fff"
                      }}
                    />
                    <Legend />
                    <Bar dataKey="Coding Score" fill="#ff4d7d" radius={[6, 6, 0, 0]} />
                  </BarChart>
                </ResponsiveContainer>
              )}
            </div>
          </div>
        </div>

        {/* Top Achievers List */}
        <div className="card">
          <h2 style={{ marginBottom: "20px" }}>Identified Top Performers Registry</h2>
          {loading ? (
            <p style={{ color: "#9ca3d5" }}>Loading outstanding profiles...</p>
          ) : topLearners.length === 0 ? (
            <p style={{ color: "#9ca3d5" }}>No top performers data returned.</p>
          ) : (
            <div style={{ overflowX: "auto" }}>
              <table>
                <thead>
                  <tr>
                    <th>Learner ID</th>
                    <th>Batch</th>
                    <th>Attendance</th>
                    <th>Coding Score</th>
                    <th>Aptitude Score</th>
                    <th>Communication Score</th>
                  </tr>
                </thead>
                <tbody>
                  {topLearners.map((item, idx) => (
                    <tr key={idx}>
                      <td style={{ fontWeight: "700", color: "#ffb800" }}>🌟 #{item.learner_id}</td>
                      <td>{item.batch}</td>
                      <td style={{ fontWeight: "600", color: "#00e38c" }}>{item.attendance_pct || 0}%</td>
                      <td>
                        <div className="progress" style={{ width: "80px", display: "inline-block", marginRight: "8px", verticalAlign: "middle" }}>
                          <div
                            className="progress-bar blue"
                            style={{ width: `${item.coding_score || 0}%` }}
                          ></div>
                        </div>
                        <span style={{ fontSize: "14px", fontWeight: "600" }}>{item.coding_score || 0}</span>
                      </td>
                      <td>
                        <div className="progress" style={{ width: "80px", display: "inline-block", marginRight: "8px", verticalAlign: "middle" }}>
                          <div
                            className="progress-bar yellow"
                            style={{ width: `${item.aptitude_score || 0}%` }}
                          ></div>
                        </div>
                        <span style={{ fontSize: "14px", fontWeight: "600" }}>{item.aptitude_score || 0}</span>
                      </td>
                      <td>
                        <div className="progress" style={{ width: "80px", display: "inline-block", marginRight: "8px", verticalAlign: "middle" }}>
                          <div
                            className="progress-bar green"
                            style={{ width: `${item.communication_score || 0}%` }}
                          ></div>
                        </div>
                        <span style={{ fontSize: "14px", fontWeight: "600" }}>{item.communication_score || 0}</span>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </div>
      </div>
    </>
  );
}

export default Analytics;