spring.application.name=learner-placement-backend
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/learner_db
spring.datasource.username=root
spring.datasource.password=student
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=my_super_secret_key_for_learner_placement_platform_which_must_be_long

# Hardcoded Admin Credentials (BCrypt hash of "admin123")
admin.email=admin@learneriq.com
admin.name=Administrator
admin.password=$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy

# Logging Configuration
logging.level.org.springframework.web=INFO
logging.level.com.backend.learner_placement=DEBUG
logging.file.name=logs/application.log
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
